### ISSUE TITLE
Do not cache "default" target

### ISSUE THREAD

**Issue by sheerun** [phenomnomnominal/mercurial-bower-resolver#3]
I think you could improve caching behavior by not skipping caching of "default" target.

So instead of:

```
        if (cached && cached.version) {
            return;
        }
```

something like:

```
        if (cached && cached.version && cached.target !== 'default') {
            return;
        }
```

or:

```
        if (cached && semver.valid(cached.target)) {
            return;
        }
```

**Comment by phenomnomnominal** [comment]
Could you tell me a bit more about how the caching works? Because you can't do anything with a mercurial repo until you've cloned the whole thing, even just a call to `releases` means a clone of the entire repo. That makes me think that the cache may just not work for mercurial. There's the potential that instead of doing the clone, I could just request the files in the .hg folder of the repo that list the tags and branches and then parse them and leave the clone up to the `fetch` but that seems like it might be less reliable.

**Comment by sheerun** [comment]
Sure!

Currently bower caches only `fetch` method result (not `releases`). We can't cache releases, because every time someone does "bower install", there's a chance there's new release. So we need to check them every time. I hope it's clear :)

As for caching result of fetch:
1. First time bower fetches given source/target pair (after resolving ranges like ~1.2.3 to specific version like 1.2.3) it doesn't pass `{ endpoint, release, version, resolution }` fields in `cached` field, because there's no cached resource yet.
2. Second time given source/target is fetched, it passes `cached` object with following fields (as described in documentation): 
- endpoint: object - endpoint of cached resource (the same format as above)
- release: string - release of cached resource
- version: string - present cached resource has been resolved as version (like 1.0.0)
- resolution: string - the “resolution” returned from previous fetch call for same resource

You can use those fields to return `undefined` from method that makes bower re-use cached resource described by `cached` field instead.

---

Also, in examples in the first post, I've used `cached.target`, instad of `cached.release`, sorry.

**Comment by phenomnomnominal** [comment]
Okay, cool, that's pretty much what I thought. I've looked into it a bit more, and as far as I can tell, `releases` will always be called, even if Bower has a version in cache. I guess that makes sense, since Bower needs to check if there's been an update. However, because of the way that Mercurial works, `releases` has to clone the whole repo again. Doesn't this means that the entire repo _always_ has to be pulled down again, defeating the point of the cache? I feel like I might be being stupid, so please let me know if I am missing something obvious :smile:

**Comment by sheerun** [comment]
You are right :) Unless there's a way to list releases without downloading whole repo (like `git ls-remote`), mercurial's version need to download whole repository each time. You can implement caching for `releases` in some way, if you want. But I'm not sure what is sensitive default. If you think we can improve Pluggable Resolvers to better support Mercurial, please let me know :)

**Comment by sheerun** [comment]
Just an idea: You can implement for example Bitbucket resolver that builds on top of MercurialResolver, but provides its own releases method that uses Bitbucket's API.

Of course it won't solve this problem in general.
